# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Tado X Exporter"
  org.opencontainers.image.description: "A simple Prometheus exporter for Tado X metrics (zone temperature/humidity/heating)."
  org.opencontainers.image.source: "https://github.com/amandolo/ha-addons/tree/main/tado-x-exporter"
  org.opencontainers.image.licenses: "GNU GPL-3.0-or-later"
args:
  TEMPIO_VERSION: "2024.11.2"