name: "Tado X Exporter"
description: "A simple Prometheus exporter for Tado X systems"
url: "https://github.com/amandolo/ha-addons/tree/main/tado-x-exporter"
version: "0.0.2"
slug: "tado_x_exporter"
init: false
arch:
  - aarch64
#  - armhf
#  - armv7
#  - amd64
#  - i386
options:
  tado_username: ""
  tado_password: ""
  tado_token_file_path: "/data/oauth_refresh_token"
  tado_exporter_port: 8080
  tado_exporter_refresh_rate: 30
schema:
  tado_username: "str"
  tado_password: "password"
  tado_token_file_path: "str"
  tado_exporter_port: "port"
  tado_exporter_refresh_rate: "int"
image: "ghcr.io/amandolo/{arch}-ha-addon-tado-x-exporter-test"
ports:
  8080/tcp: 8080

